[package]
name = "podpower"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "podpower"
path = "src/main.rs"

[dependencies]
btleplug = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
